name: Build and Package

on:
  push:
    tags:
      - "v*" # Trigger only for tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Executable
        run: npm run build # Add your build script here

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/my-app-${{github.ref }}.zip
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}